# Generated by Django 5.2.4 on 2025-07-15 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('content', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Содержимое')),
            ],
            options={
                'verbose_name': 'Дневник',
                'verbose_name_plural': 'Дневники',
                'ordering': ['head', 'content', 'owner'],
            },
        ),
        migrations.CreateModel(
            name='DiaryEntries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('content', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Содержимое')),
                ('publication_status', models.BooleanField(blank=True, default=False, help_text='Публиковать на первую страницу?', null=True, verbose_name='Статус публикации')),
                ('views_counter', models.PositiveIntegerField(default=0, verbose_name='Счетчик просмотров')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['head', 'content', 'owner', 'diary', 'publication_status'],
            },
        ),
    ]
