# Generated by Django 5.2.4 on 2025-07-15 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='diaryentries',
            name='diary',
            field=models.ForeignKey(blank=True, default=None, help_text='Выберите название Дневника, в котором будет лежать эта запись', null=True, on_delete=django.db.models.deletion.SET_NULL, to='diary.diary', verbose_name='Дневник'),
        ),
        migrations.AddField(
            model_name='diaryentries',
            name='owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
    ]
