# Generated by Django 5.2.4 on 2025-07-15 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='content',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Содержимое дневника'),
        ),
    ]
