# Generated by Django 5.1.6 on 2025-07-27 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_alter_diary_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diaryentries',
            options={'ordering': ['head', 'content', 'owner', 'diary', 'publication_status'], 'verbose_name': 'Записи в дневнике', 'verbose_name_plural': 'Записи в дневникае'},
        ),
    ]
