# Generated by Django 5.2.4 on 2025-07-28 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_alter_diaryentries_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diaryentries',
            options={'ordering': ['head', 'content', 'owner_entries', 'diary', 'publication_status'], 'verbose_name': 'Записи в дневнике', 'verbose_name_plural': 'Записи в дневникае'},
        ),
        migrations.RemoveField(
            model_name='diaryentries',
            name='owner',
        ),
        migrations.AddField(
            model_name='diaryentries',
            name='owner_entries',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
    ]
